name: Push Docker Image to ACR

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

env:
  CONTAINER_REGISTRY: sharatest1.azurecr.io
  image_name: githubactions-aks-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: dotnet build
        run: dotnet build -c release
      
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:

          username: ${{ secrets.ACR_USERNAME }}

          password:  ${{ secrets.ACR_PASSWORD}}
       
          login-server: ${{env.CONTAINER_REGISTRY}}

      - name: Push Container to 
        run: |
          docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.image_name}}:'${{github.sha}}' .
          docker push ${{env.CONTAINER_REGISTRY}}/${{env.image_name}}:'${{github.sha}}'
      
   #   - name: Azure Kubernetes set context
   #     uses: azure/aks-set-context@v1
   #     with: 
   #       creds: '${{secrets.AZURE_CREDENTIALS}}'
   #       resource-group: github-test
   #        cluster-name: .....

      
      # Create K8S secrets to pull images
  #    - name: create secret in kubernetes cluster
  #      uses: Azure/k8s-create-secret@v1.1
  #      with:
  #        container-registry-url: ${{env.CONTAINER_REGISTRY}}
  #        container-registry-username: ${{ secrets.ACR_USERNAME }}
  #        container-registry-password: ${{ secrets.ACR_PASSWORD }}
  #        secret-type: docker-registry
  #        secret-name: acr-image-pull-secret
      
      # Deploy to K8S Cluster
  #    - name: Deploy to Kubernetes cluster
  #      uses: Azure/k8s-deploy@v1
  #      with:
          # Path to the manifest files which will be used for deployment.
  #        manifests: |
  #          k8s/deplyment.yml
  #          k8s/service.yml
          # fully qualified resource url of the image
  #        images: ${{env.CONTAINER_REGISTRY}}/${{env.image_name}}:'${{github.sha}}'
          # Name of a docker-registry secret that has already been set up within the cluster.
  #        imagepullsecrets: acr-image-pull-secret
          # deploy/promote/reject
  #        action: deploy